# server config
server:
  port: 8081
  servlet:
    context-path: /consumer
# log config
logging:
  level:
    com.: debug
  file:
    path: /log.log
dubbo:
  application:
    name: boot-dubbo-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 1000